//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.ServiceImport {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceImport.IServiceImport")]
    public interface IServiceImport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceImport/Import", ReplyAction="http://tempuri.org/IServiceImport/ImportResponse")]
        void Import();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceImport/Import", ReplyAction="http://tempuri.org/IServiceImport/ImportResponse")]
        System.Threading.Tasks.Task ImportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceImport/ImportFromArla", ReplyAction="http://tempuri.org/IServiceImport/ImportFromArlaResponse")]
        void ImportFromArla();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceImport/ImportFromArla", ReplyAction="http://tempuri.org/IServiceImport/ImportFromArlaResponse")]
        System.Threading.Tasks.Task ImportFromArlaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceImportChannel : GUI.ServiceImport.IServiceImport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceImportClient : System.ServiceModel.ClientBase<GUI.ServiceImport.IServiceImport>, GUI.ServiceImport.IServiceImport {
        
        public ServiceImportClient() {
        }
        
        public ServiceImportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceImportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceImportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceImportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Import() {
            base.Channel.Import();
        }
        
        public System.Threading.Tasks.Task ImportAsync() {
            return base.Channel.ImportAsync();
        }
        
        public void ImportFromArla() {
            base.Channel.ImportFromArla();
        }
        
        public System.Threading.Tasks.Task ImportFromArlaAsync() {
            return base.Channel.ImportFromArlaAsync();
        }
    }
}
