//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWCFService.ServiceRoute {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRoute.IServiceRoute")]
    public interface IServiceRoute {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoute/GetRoutes", ReplyAction="http://tempuri.org/IServiceRoute/GetRoutesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFService.ExceptionNoRoutes), Action="http://tempuri.org/IServiceRoute/GetRoutesExceptionNoRoutesFault", Name="ExceptionNoRoutes", Namespace="http://schemas.datacontract.org/2004/07/WCFService")]
        Model.Route[] GetRoutes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoute/GetRoutes", ReplyAction="http://tempuri.org/IServiceRoute/GetRoutesResponse")]
        System.Threading.Tasks.Task<Model.Route[]> GetRoutesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRouteChannel : TestWCFService.ServiceRoute.IServiceRoute, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRouteClient : System.ServiceModel.ClientBase<TestWCFService.ServiceRoute.IServiceRoute>, TestWCFService.ServiceRoute.IServiceRoute {
        
        public ServiceRouteClient() {
        }
        
        public ServiceRouteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRouteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRouteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRouteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Model.Route[] GetRoutes() {
            return base.Channel.GetRoutes();
        }
        
        public System.Threading.Tasks.Task<Model.Route[]> GetRoutesAsync() {
            return base.Channel.GetRoutesAsync();
        }
    }
}
